import Head from 'next/head'
import Navbar from './components/navbar/Navbar'
import Sidebar from './components/Sidebar/Sidebar'
import styles from '../styles/Home.module.css'
import OverlayText from './components/OverlayText/OverlayText'
import Footer from './components/footer/Footer'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BEAUTY SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
     
      <Navbar />
      <OverlayText />
      <Sidebar />
     
      </main>

      <footer className={styles.footer}>
      <Footer />
      </footer>
    </div>
  )
}
