import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Banner from '../components/banner/Banner'
import Footer from '../components/footer/Footer'
import Beauty from '../components/beauty/Beauty'
import ReleventProduct from '../components/singleProduct/ReleventProduct';
import SeeMoreBtn from '../components/SeeMoreBtn/SeeMoreBtn'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BEAUTY SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <Banner />
        <ReleventProduct />
        <SeeMoreBtn />
         <Beauty />
      
      </main>

      <footer className={styles.footer}>
      <Footer />
      </footer>
    </div>
  )
}
